// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: ad_tool_overpass.proto

package ad_tool_overpass

import (
	ad_base_overpass "github.com/zbwang163/ad_base_overpass"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MakeVideoByTemplateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TemplateId string                        `protobuf:"bytes,1,opt,name=TemplateId,proto3" json:"TemplateId,omitempty"`                                                                                        // 模板id
	Materials  map[int32]string              `protobuf:"bytes,2,rep,name=materials,proto3" json:"materials,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 时间为key，素材为value，图片是url，视频是vid
	Base       *ad_base_overpass.BaseRequest `protobuf:"bytes,15,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *MakeVideoByTemplateRequest) Reset() {
	*x = MakeVideoByTemplateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_tool_overpass_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeVideoByTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeVideoByTemplateRequest) ProtoMessage() {}

func (x *MakeVideoByTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ad_tool_overpass_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeVideoByTemplateRequest.ProtoReflect.Descriptor instead.
func (*MakeVideoByTemplateRequest) Descriptor() ([]byte, []int) {
	return file_ad_tool_overpass_proto_rawDescGZIP(), []int{0}
}

func (x *MakeVideoByTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *MakeVideoByTemplateRequest) GetMaterials() map[int32]string {
	if x != nil {
		return x.Materials
	}
	return nil
}

func (x *MakeVideoByTemplateRequest) GetBase() *ad_base_overpass.BaseRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

type MakeVideoByTemplateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *MakeVideoByTemplateResponse_MakeVideoByTemplateData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Base *ad_base_overpass.BaseResponse                       `protobuf:"bytes,15,opt,name=base,proto3" json:"base,omitempty"`
}

func (x *MakeVideoByTemplateResponse) Reset() {
	*x = MakeVideoByTemplateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_tool_overpass_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeVideoByTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeVideoByTemplateResponse) ProtoMessage() {}

func (x *MakeVideoByTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ad_tool_overpass_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeVideoByTemplateResponse.ProtoReflect.Descriptor instead.
func (*MakeVideoByTemplateResponse) Descriptor() ([]byte, []int) {
	return file_ad_tool_overpass_proto_rawDescGZIP(), []int{1}
}

func (x *MakeVideoByTemplateResponse) GetData() *MakeVideoByTemplateResponse_MakeVideoByTemplateData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MakeVideoByTemplateResponse) GetBase() *ad_base_overpass.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

type MakeVideoByTemplateResponse_MakeVideoByTemplateData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // 对materials有序取hash后的hash值
}

func (x *MakeVideoByTemplateResponse_MakeVideoByTemplateData) Reset() {
	*x = MakeVideoByTemplateResponse_MakeVideoByTemplateData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ad_tool_overpass_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeVideoByTemplateResponse_MakeVideoByTemplateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeVideoByTemplateResponse_MakeVideoByTemplateData) ProtoMessage() {}

func (x *MakeVideoByTemplateResponse_MakeVideoByTemplateData) ProtoReflect() protoreflect.Message {
	mi := &file_ad_tool_overpass_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeVideoByTemplateResponse_MakeVideoByTemplateData.ProtoReflect.Descriptor instead.
func (*MakeVideoByTemplateResponse_MakeVideoByTemplateData) Descriptor() ([]byte, []int) {
	return file_ad_tool_overpass_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MakeVideoByTemplateResponse_MakeVideoByTemplateData) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_ad_tool_overpass_proto protoreflect.FileDescriptor

var file_ad_tool_overpass_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x64, 0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x70, 0x61,
	0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x61, 0x64, 0x5f, 0x62, 0x61, 0x73,
	0x65, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x70, 0x61, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xe6, 0x01, 0x0a, 0x1a, 0x4d, 0x61, 0x6b, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x79,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12,
	0x48, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x79,
	0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09,
	0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x20, 0x0a, 0x04, 0x62, 0x61, 0x73,
	0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x1a, 0x3c, 0x0a, 0x0e, 0x4d,
	0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xbb, 0x01, 0x0a, 0x1b, 0x4d, 0x61,
	0x6b, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x42, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42,
	0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x1a, 0x2f, 0x0a, 0x17, 0x4d, 0x61, 0x6b, 0x65, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x42, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0x61, 0x0a, 0x0b, 0x54, 0x6f, 0x6f, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x52, 0x0a, 0x13, 0x4d, 0x61, 0x6b, 0x65, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x42, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e,
	0x4d, 0x61, 0x6b, 0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x4d, 0x61, 0x6b,
	0x65, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x42, 0x79, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x62, 0x77, 0x61, 0x6e, 0x67, 0x31,
	0x36, 0x33, 0x2f, 0x61, 0x64, 0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x5f, 0x6f, 0x76, 0x65, 0x72, 0x70,
	0x61, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ad_tool_overpass_proto_rawDescOnce sync.Once
	file_ad_tool_overpass_proto_rawDescData = file_ad_tool_overpass_proto_rawDesc
)

func file_ad_tool_overpass_proto_rawDescGZIP() []byte {
	file_ad_tool_overpass_proto_rawDescOnce.Do(func() {
		file_ad_tool_overpass_proto_rawDescData = protoimpl.X.CompressGZIP(file_ad_tool_overpass_proto_rawDescData)
	})
	return file_ad_tool_overpass_proto_rawDescData
}

var file_ad_tool_overpass_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ad_tool_overpass_proto_goTypes = []interface{}{
	(*MakeVideoByTemplateRequest)(nil),  // 0: MakeVideoByTemplateRequest
	(*MakeVideoByTemplateResponse)(nil), // 1: MakeVideoByTemplateResponse
	nil,                                 // 2: MakeVideoByTemplateRequest.MaterialsEntry
	(*MakeVideoByTemplateResponse_MakeVideoByTemplateData)(nil), // 3: MakeVideoByTemplateResponse.MakeVideoByTemplateData
	(*ad_base_overpass.BaseRequest)(nil),                        // 4: BaseRequest
	(*ad_base_overpass.BaseResponse)(nil),                       // 5: BaseResponse
}
var file_ad_tool_overpass_proto_depIdxs = []int32{
	2, // 0: MakeVideoByTemplateRequest.materials:type_name -> MakeVideoByTemplateRequest.MaterialsEntry
	4, // 1: MakeVideoByTemplateRequest.base:type_name -> BaseRequest
	3, // 2: MakeVideoByTemplateResponse.data:type_name -> MakeVideoByTemplateResponse.MakeVideoByTemplateData
	5, // 3: MakeVideoByTemplateResponse.base:type_name -> BaseResponse
	0, // 4: ToolService.MakeVideoByTemplate:input_type -> MakeVideoByTemplateRequest
	1, // 5: ToolService.MakeVideoByTemplate:output_type -> MakeVideoByTemplateResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ad_tool_overpass_proto_init() }
func file_ad_tool_overpass_proto_init() {
	if File_ad_tool_overpass_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ad_tool_overpass_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeVideoByTemplateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ad_tool_overpass_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeVideoByTemplateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ad_tool_overpass_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeVideoByTemplateResponse_MakeVideoByTemplateData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ad_tool_overpass_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ad_tool_overpass_proto_goTypes,
		DependencyIndexes: file_ad_tool_overpass_proto_depIdxs,
		MessageInfos:      file_ad_tool_overpass_proto_msgTypes,
	}.Build()
	File_ad_tool_overpass_proto = out.File
	file_ad_tool_overpass_proto_rawDesc = nil
	file_ad_tool_overpass_proto_goTypes = nil
	file_ad_tool_overpass_proto_depIdxs = nil
}
